name: Detect Changes
description: Defines variables indicating the parts of the code that changed
outputs:
  isApp:
    description: True when changes happened to app code
    value: '${{ steps.diff.outputs.isApp }}'

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # Pin v4.1.1
    - name: Detect Changes
      uses: dorny/paths-filter@v3
      id: diff
      with:
        filters: |
          isApp:
            - 'sdk/src/**'
